### ISSUE TITLE
Positioning within content_box

### ISSUE THREAD

**Issue by Purple906** [Purple906/Marks_Panara#1]
@mysterycommand I'm having trouble with the positioning of my elements within the "content_box" I have them all, for the time being, how I want them looking, but they are in the wrong spots. 

I want the "#saying" to be below the photo (roughly 10px), and the #story to wrap up and around the photo and #saying on the right side. Then the ".products" to be centered along the bottom.  

I remember doing something with the display and position tags, but even when I go back and review and do what they say, it doesn't seem to be working right. I thought if I made the position:absolute for the content_box, the children of that element would position themselves off of it ... but when I adjust the display or position of some of the children, it either doesn't move or moves to someplace I wouldn't have thought it would go.

**Comment by mysterycommand** [comment]
Okay, couple things going on here:
1. The current "best practice" is to use the `class` attribute on your HTML elements (and CSS selectors like `.saying` and `.story` etc.) instead of `id`s and selectors like `#saying`. Basically, you want to be as unspecific as possible at all times with your CSS … I know that sounds weird, but it'll start to make sense as you get into it more.
2. If you want the image and the saying grouped together, I'd put them both together inside a `div`, and `float` that `div`.
3. The paragraphs inside the `#story` element should each be it's own `p` tag. Semantically it's more correct A.so you can use CSS to set the [`text-indent`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent) on `p` tags in general, and get rid of all those `&nbsp;` characters.
4. The CSS position properties work a little differently than you're thinking about. I think what you want is is the `#displays` element to have `width: 100%;` (which will make it the full width of it's parent). The `.products` will probably just need to be `display: inline-block;` at that point.
5. Finally, you could install a Sublime Text plugin called HTML-CSS-JS Prettify … I'm about to create a pull request with the results of running that plugin on your `index.html`.

Hope that helps. As far as positioning goes, `position: absolute;` applies to the thing you want to position, and it's parent should be `position: relative;` … [this article might help](https://css-tricks.com/absolute-relative-fixed-positioining-how-do-they-differ/)? There's a link in that article to a longer description that might help too. Let me know if you need more detail on anything!

**Comment by mysterycommand** [comment]
Did this help? You can close the issue if you think it's solved/done/not an issue anymore. @Purple906
